// <auto-generated />
namespace EAP_ASM_NTT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCoin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCoin));
        
        string IMigrationMetadata.Id
        {
            get { return "202001061013382_AddCoin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
